name: todos_crud_pet
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  dio: ^5.7.0
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0
  uuid: ^4.4.2
  shared_preferences: ^2.3.3
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl_utils: ^2.8.7

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env